<?php
require_once __DIR__ . '/../../vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;

function generateFacultyPDF($name, $email) {
    $options = new Options();
    $options->set('isHtml5ParserEnabled', true);
    $dompdf = new Dompdf($options);

    $html = "
    <html>
    <head>
        <style>
            body { font-family: sans-serif; }
            .header { text-align: center; border-bottom: 2px solid #2a498b; padding-bottom: 10px; margin-bottom: 20px; }
            .content { margin: 20px; }
            .footer { margin-top: 50px; font-size: 10px; text-align: center; color: #777; }
        </style>
    </head>
    <body>
        <div class='header'>
            <h1>Faculty Information</h1>
        </div>
        <div class='content'>
            <p><strong>Name:</strong> $name</p>
            <p><strong>Email:</strong> $email</p>
            <p>Welcome to the Online Exam Management System. This document contains your registered details.</p>
        </div>
        <div class='footer'>
            Generated by Online Exam Management System
        </div>
    </body>
    </html>";

    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    return $dompdf->output();
}
?>
